language: python
python:
    -"3.5"

branches:
    only:
        -dev

install:
    -pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"

services:
    - postgresql

script:
    - ./manage.py test
